### ISSUE TITLE
"Active" content (and Graphviz)

### ISSUE THREAD

**Issue by skreisel** [nextcloud/cms_pico#222]
Hi. 
Pico CMS doesn't allow ["active" content](https://github.com/nextcloud/cms_pico#html-in-markdown-files) and strips the html via [HTML purifier](http://htmlpurifier.org/) / and doesn't allow SVG.
I would love to host a clickable [Graphviz](https://graphviz.org/Gallery/gradient/cluster.svg) graph; the usual way would be to export a graph via SVG. One could, however, also export using the html <map> tag. Unfortunately, that tag gets removed as "active" as well. As far as googable, the html <map> tag is not "active"...
Any ideas? Twig?
Cheers!

**Comment by skreisel** [comment]
Hi - sorry for the delay in responding. 
Graphviz exports via `<svg>`; that's active content and is prohibited in the Nextcloud Pico CMS setup; Graphviz can also export using the html `<map>` tag (somehow that specific piece of information got lost in my first post) - which doesn't seem to pose a security risk!? 
That would allow the graph to be "clickable" -> eg one could click on a node in the graph and have the html link opened as in:
```
<map name="workmap">
  <area shape="rect" coords="34,44,270,350" alt="Computer" href="computer.htm">
  <area shape="rect" coords="290,172,333,250" alt="Phone" href="phone.htm">
  <area shape="circle" coords="337,300,44" alt="Cup of coffee" href="coffee.htm">
</map>
```
Cheers

**Comment by PhrozenByte** [comment]
I see. Next to `<map>` you use `<img>` to include the actual image, right? Yeah, sounds reasonable.

I can think of three approaches:
1. Create a simple Pico plugin, hook into the [`onHtmlPurifier` event](https://github.com/nextcloud/cms_pico/blob/v1.0.21/lib/Pico.php#L243) and add a whitelist config for the `<map>` and `<area>` tags with their required attributes. I can't guarantee that `<map>` is really safe. I'd guess so, but no guarantee.

3. Create a custom theme and create both the `<img>` and `<map>` tags according to some YAML metadata, e.g. (untested!)
    ```yaml
    ---
    graphviz:
        image: %assets_url%/path_to_graphviz.svg
        map:
            - shape: rect
              coords: 34,44,270,350
              href: computer.htm
            - shape: rect
              coords: 290,172,333,250
              href: phone.htm
    ---
    ```
    ```twig
    {% if meta.graphviz %}
        <img src="{{ meta.graphviz.image|url }}" alt="" usemap="#graphviz" />
        {% if meta.graphviz.map %}
            <map name="graphviz">
                {% for map in meta.graphviz.map %}
                    <area shape="{{ map.shape|e("html_attr") }}" coords="{{ map.coords|e("html_attr") }}" href="{{ map.href|url }}" />
                {% endfor %}
            </map>
        {% endif %}
    {% endif %}
    ```

5. If you're rather just trying to add a single Graphviz graph, you could also simply dump the whole SVG in a Twig template (however, please note that all themes can be used by all users).
